apiVersion: v1
imagePullSecrets:
- name: kafka-cluster-kafka-exporter-dockercfg-f5v58
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: kafka-cluster
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: strimzi
    app.kubernetes.io/part-of: strimzi-kafka-cluster
    strimzi.io/cluster: kafka-cluster
    strimzi.io/kind: Kafka
  name: kafka-cluster-kafka-exporter
  ownerReferences:
  - apiVersion: kafka.strimzi.io/v1beta1
    blockOwnerDeletion: false
    controller: false
    kind: Kafka
    name: kafka-cluster
    uid: 1c56e00c-dda3-11ea-a9b2-005056b0841c
secrets:
- name: kafka-cluster-kafka-exporter-token-9f2bv
- name: kafka-cluster-kafka-exporter-dockercfg-f5v58
