apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    app: strimzi
  name: kafka-service-monitor
spec:
  endpoints:
  - honorLabels: true
    interval: 10s
    path: /metrics
    port: prometheus
    relabelings:
    - action: keep
      regex: prometheus-kube-state-metrics
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_endpoints_name
    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)
      replacement: $1
      separator: ;
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_namespace
      targetLabel: namespace
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_namespace
      targetLabel: kubernetes_namespace
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_service_name
      targetLabel: kubernetes_name
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node_name
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_pod_host_ip
      targetLabel: node_ip
    scheme: http
    scrapeTimeout: 10s
  - honorLabels: true
    interval: 10s
    path: /metrics
    port: prometheus
    relabelings:
    - action: keep
      regex: prometheus-node-exporter
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_endpoints_name
    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)
      replacement: $1
      separator: ;
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_namespace
      targetLabel: namespace
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_namespace
      targetLabel: kubernetes_namespace
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_service_name
      targetLabel: kubernetes_name
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node_name
    - action: replace
      regex: (.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - __meta_kubernetes_pod_host_ip
      targetLabel: node_ip
    scheme: http
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - amq-kafka-test
  selector:
    matchLabels:
      strimzi.io/kind: Kafka
