apiVersion: v1
data:
  prometheus.yaml.gz: H4sIAAAAAAAA/+xaTY/jKBO+51egUR+SbjnuzMzJObRead7DaLUzfd8PRHAloWMDCzjbvdPz31fGdmInOLbzvVIurQ6GqqeKongKmEViQqKghxAsSZQQwwTHjBtQSxIF6NOj7iGkqSIStprh1YDiJMIRmUCkUyEISSViMHNIdIBI/Je3INMF8UJY+usvGx2xAhkxSgJ013/+/gV/+9+v/x/0VBIBnrIIdNDzkA+GliT46VddavBK/6bf7EDv0b8fvpE46uUWUMGnbGYFvogJ5iSGTZTZfxrUklHwYsGZEcp/7CE0F1yowlZkVAI9hBbJBBQHAxrrcC0fIQ8pEUGAgIdSMG4yo1ONWhIKubfyluKHh+I3qcQLUONy+6g8G4bFIBJTtMZgFKMaS2LmAfLzn7b7HFIz58bIHkIKrAVVqISm8x6gBYC0ULRIFIXKxHoI4xgMwWWTMzdl/bA2isX/MMwEXjAe2lEKZvAaoF9Srx6kqvAjlkIZO3Nl+ZXY8jrLJGGoQGtsiJqBWaPvMmgFSYMkihihAjQuY/wmQhj3h/eDvFFGhEIM3ATo7sfop23NZVngAeIihOu151mE3cyRIuxizWqtuDxT+tZaYBGtK8uqMvPPXSRKEdZJ62hsA7YXMal1s7fRt5jQ7QGHrRLdHBKlJJwK8LQhBrx1Lto0YGTbNlKCVyu+KQH1hw+uaKxqsV1jIvcPxS149bG5gl6zUKrQ8m8nQ1Y77sQgt4K7G85zQLQrWYTtMVY7nwHdXGiDmWyNLe+6D7Ku7Gh0Y0c3dnRjRzd2dGNHLdlRGrsevKarFdSNGN2I0Y0Y/deI0RqFR0m4ZFqoOhp0fKqi25CrfIOs51Xotz96CE2AKFDYiAVwe+AWIH9JlK8S7mugCoz217qGTPh52BJKRcKNb0f2EDKRzmFkaijZSxwlQ6qy/My4BpoowHrBJF6CYtO3lVedXK19hrSxsHd6rFGziqZq3OEVfcDbekrOCGFKksgM9ZIGnz9/OjgH7l63K8wPbszlSHQB94lk/nLkp2q0n+63vlTi9a2IWb+0Ls5ih9P3m/nouLtMKryY2688Ow//+rw3zlVuaoMyczN2rwMX/goh6wivjte1dmgdKWorzOIIldjBT6jghjAOai0xnbT0Rx6/tWz9+5fxenSfg/lbqMVgeO/whEPLQVHlkLcDZqO+zi6qU/bn3YG6Wnl+2+vYUIkTTWaAjTAkejdELzS2Z4nvVCb5Nw1U8FDnfWKIhXrDU8KiREHRWkhMworE5mRvDavZ7aUI9fl2+jYbfVZNNe3z7fOEm2cRzoXJLghLd3dM4My6nbP8IfXPhw6FzhFgpW49zcZ3HN5aD1zk9Kdu5HrNVI97aldyf/gwHt4P3vvj4X1u3KB5dTfNRpXT7G/mrvkJ+k/B7+HDYNxP/3alViknCe5+fPzZeVty23LZarqBP2wUrsevAi/FHI5WqF6QKDYWqsclhzVbl2Xq9mougs5n6Lf6s0X96Vj+nWrQzePK/SvHPaurUxeFdaGZT8LVMCsimT2eAxUgnkRRZmmHS6vDSdc5jpabGPzFHgN0BVYcpV4hS20BLY3K3fuCzbpP7jWZjT8NU20Ef000u5mRNpvThpX2n4JDWOkouPt4BEZ6HXc8F2SlByHbcedz5jueTjhv1Pnk56pXVhVeqvYiESjDuCXT9n/3SbPrfNbBAYpH3oWwmHAyA5ULsVuAVDBlrwHyM0urVG0HWat7TuTiZhtPiqwB5RdOOfgtO52Pc5zPc1pmgZWLyt44gqKal0Budf8GAAD//7TlWPX+LwAA
kind: Secret
metadata:
  annotations:
    generated: "true"
  labels:
    managed-by: prometheus-operator
  name: prometheus-prometheus
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Prometheus
    name: prometheus
    uid: 536a4215-623d-11eb-a398-005056b0841c
type: Opaque
